### ISSUE TITLE
Add build subcommand to transaction

### ISSUE THREAD

**Issue by thisHermit** [blockfrost/blockfrost-cardano-cli#17]
It would make it quite convenient to have a `build` sub command like cardano-cli to make a transaction. Also since it requires a local node running (https://github.com/input-output-hk/cardano-node/blob/master/cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs#L432) it would be a nice fit.

**Comment by mmahut** [comment]
Try to use the `build-raw` sub command to build your transaction, it should not require the local node running.

**Comment by thisHermit** [comment]
Yes, I am using it. I just thought that it would make building transactions a bit more convenient. Like calculating min fees, execution units, etc.

**Comment by mmahut** [comment]
Building transactions is a complex task, so we do not plan to include this into the cli at the moment.
